### ISSUE TITLE
Error when injecting SpanContext into carrier. 

### ISSUE THREAD

**Issue by Vinnikau** [rsocket/rsocket-rpc-java#76]
Error when injecting SpanContext into carrier.
I have 2 services client/server Rsocket RPC, WebFlux. I add Jaeger opentracing-spring-jaeger-cloud-starter

I try to communicate by RSocket:
```
rSocketClient.source()
                .flatMap(rSocket -> new IdentityProviderRSocketClient(rSocket, tracer)
                        .checkClientProfile(request))
```

Got it with an error in to client size:

java.lang.ClassCastException: class io.opentracing.propagation.TextMapInjectAdapter cannot be cast to class io.opentracing.propagation.TextMap (io.opentracing.propagation.TextMapInjectAdapter and io.opentracing.propagation.TextMap are in unnamed module of loader 'app')
	at io.jaegertracing.internal.propagation.TextMapCodec.inject(TextMapCodec.java:37) ~[jaeger-core-1.1.0.jar:1.1.0]
	at io.jaegertracing.internal.PropagationRegistry$ExceptionCatchingInjectorDecorator.inject(PropagationRegistry.java:75) ~[jaeger-core-1.1.0.jar:1.1.0]
	at io.jaegertracing.internal.JaegerTracer.inject(JaegerTracer.java:208) ~[jaeger-core-1.1.0.jar:1.1.0]
	at io.rsocket.ipc.tracing.SpanSubscriber.<init>(SpanSubscriber.java:122) ~[rsocket-ipc-core-0.3.0.jar:na]
	at io.rsocket.ipc.tracing.Tracing.lambda$null$0(Tracing.java:137) ~[rsocket-ipc-core-0.3.0.jar:na]
	at reactor.core.publisher.Operators$LiftFunction.lambda$liftScannable$1(Operators.java:2526) ~[reactor-core-3.4.11.jar:3.4.11]
	at reactor.core.publisher.MonoLift.subscribeOrReturn(MonoLift.java:41) ~[reactor-core-3.4.11.jar:3.4.11]
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:57) ~[reactor-core-3.4.11.jar:3.4.11]
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:157) ~[reactor-core-3.4.11.jar:3.4.11]
	at io.opentracing.contrib.reactor.TracedSubscriber.lambda$onNext$2(TracedSubscriber.java:69) ~[opentracing-reactor-0.1.0.jar:na]
	at io.opentracing.contrib.reactor.TracedSubscriber.withActiveSpan(TracedSubscriber.java:95) ~[opentracing-reactor-0.1.0.jar:na]
	...

These lines use an object of the class io.opentracing.propagation.TextMapInjectAdapter - it is not inherited from TextMap:

https://github.com/rsocket/rsocket-rpc-java/blob/c3c47723ad85af9c7ba2edbf27494c7f1835a893/rsocket-rpc-core/src/main/java/io/rsocket/rpc/tracing/SpanSubscriber.java#L76

https://github.com/rsocket/rsocket-rpc-java/blob/c3c47723ad85af9c7ba2edbf27494c7f1835a893/rsocket-rpc-core/src/main/java/io/rsocket/rpc/tracing/SpanSubscriber.java#L123

In the method:
`<C> void inject (SpanContext var1, Format <C> var2, C var3)`

It is required to pass the adapter of the TextMap class:
`Format <TextMap> TEXT_MAP`

The io.opentracing.contrib.spring.cloud.websocket.TextMapInjectAdapter class was probably intended to be used.
I think this is the problem. Please, help.

**Comment by Vinnikau** [comment]
All these problems are due to mismatching versions of the trace api.

RSocket use opentrace-api version 0.31.0
opentracing-spring-jaeger-cloud-starter since version 2.0.0 use opentrace-api version 0.32.0 and 0.33.0
